"use client";

import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { TourStep } from "./TourStep";
import { UIHighlight } from "./UIHighlight";

const TOUR_STORAGE_KEY = "inverse.arena-v2.onboarding-complete";

type OnboardingStep = {
  title: string;
  description: string;
  note?: string;
  icon: string;
  anchors: string[];
  showPointers?: boolean;
};

const STEPS: OnboardingStep[] = [
  {
    title: "THE OBJECTIVE",
    description:
      "Survival is a game of numbers. In the Inverse Arena, the majority is eliminated. Your goal is to choose the side with fewer players and remain in the arena.",
    icon: "▦",
    anchors: ["center-area"],
  },
  {
    title: "CHOOSE WISELY",
    description:
      "Decision speed is critical. You must select HEADS or TAILS before the round timer reaches zero.",
    note: "Risk alert: your principal and RWA yield are tracked in real time while you compete.",
    icon: "↻",
    anchors: ["timer", "selection-cards"],
    showPointers: true,
  },
  {
    title: "THE REWARD",
    description:
      "While you are in the arena, your funds generate Real-World Asset (RWA) yield every millisecond.",
    note: "The Live Pot displays collective yield generated by all active players in real time.",
    icon: "¤",
    anchors: ["yield-pot"],
    showPointers: true,
  },
];

export function OnboardingTour() {
  const [isOpen, setIsOpen] = useState<boolean | null>(() => {
    if (typeof window === "undefined") {
      return null;
    }

    const completed = window.localStorage.getItem(TOUR_STORAGE_KEY) === "true";
    return !completed;
  });
  const [stepIndex, setStepIndex] = useState(0);

  const closeAndPersist = () => {
    window.localStorage.setItem(TOUR_STORAGE_KEY, "true");
    setIsOpen(false);
  };

  useEffect(() => {
    if (!isOpen) {
      return;
    }

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        closeAndPersist();
      }
    };

    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [isOpen]);

  const currentStep = useMemo(() => STEPS[stepIndex], [stepIndex]);

  if (!isOpen || currentStep === undefined) {
    return null;
  }

  return (
    <div className="fixed inset-0 z-[100]">
      <UIHighlight anchors={currentStep.anchors} {...(currentStep.showPointers !== undefined && { showPointers: currentStep.showPointers })} />

      <div className="pointer-events-none absolute inset-0 flex items-center justify-center p-4 sm:p-8">
        <AnimatePresence mode="wait" initial={false}>
          <motion.div
            key={stepIndex}
            className="pointer-events-auto"
            initial={{ opacity: 0, y: 24, scale: 0.98 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: -10, scale: 0.98 }}
            transition={{ duration: 0.22, ease: "easeOut" }}
          >
            <TourStep
              stepNumber={stepIndex + 1}
              totalSteps={STEPS.length}
              title={currentStep.title}
              description={currentStep.description}
              note={currentStep.note}
              icon={currentStep.icon}
              isFirst={stepIndex === 0}
              isLast={stepIndex === STEPS.length - 1}
              onPrevious={() => setStepIndex((prev) => Math.max(0, prev - 1))}
              onNext={() => {
                if (stepIndex === STEPS.length - 1) {
                  closeAndPersist();
                  return;
                }
                setStepIndex((prev) => Math.min(STEPS.length - 1, prev + 1));
              }}
              onSkip={closeAndPersist}
            />
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  );
}
